### PR TITLE
BIG MAP compose page!

### PR DESCRIPTION
**Pull request by ian-ross**
This is a big PR based on the work that @linzjax has been doing over the last few weeks.  It removes the "wizard" part of the "Make an atlas" workflow, replacing it with a single "big map" view with a UI panel on the left-hand side containing all of the controls that were previously on separate pages.

We're aware that this is a big change and that there are a number of questions to be answered before it can be merged.  This PR is for discussion, and we're going to be doing the following things this week to facilitate that discussion:

1. Creating UI mocks for a number of options for the left-hand side panel of the atlas composer page.
2. Making interactive demonstrators of different interaction models for the page composer grid ("interactive demonstrator" here means "a custom Field Papers site that's identical in all respects to the real one except that the page composer grid behaves differently").
3. Making a survey to allow people to offer their opinions on these different options.
4. Deploying an "experimental" version of Field Papers to a temporary AWS site so that people can examine all these different options.  There will be links to the UI mocks, the possibility to experiment with the different page composer grid interaction models, and a link to the survey to collect opinions and ideas.
5. Publicising the experimental site and proposed changes in places where interested people are likely to gather (OSM mailing lists, etc.).

We're aiming to get that done this week, but in the meantime, comments on the PR would be much appreciated!

### CODE REVIEW

**Comment by ian-ross** [comment]
We've put up a custom version of Field Papers at http://fieldpapers-demo.cadasta.org that showcases the new "big map" layout for the atlas page composer.  There are links there to some UI mocks and a survey to get feedback on the different options that @linzjax has implemented.

Let us know what you think, and publicise as you think fit.  We've not yet done any translations of the text on the front page, but we can do that.  Same goes for the survey: just let us know what languages are needed and we'll get on it (comments here or shoot me an email).

Once we get some feedback from users (and from people currently involved in Field Papers development, especially on design issues), we'll review and update the PR!

**Comment by ericsoco** [comment]
Definitely cleaner, nice work folks!

Re: Grid Layout, adding/removing columns shouldn't change the size of the bounding box. Seems like the workflow should be:

1. Draw a rect around the area to be mapped.
2. Subdivide the rect as necessary.

The font size for the location search field is too small. Let it scroll horizontally.

Also, would be nice to see a UTM grid overlay in the FP UI instead of having to wait until the PDF is generated. Additional work, probably beyond the scope of this PR, but.

The breathing room you've given the map here is SO MUCH BETTER. :+1:

**Comment by ericsoco** [comment]
One problem with the dewizardification -- it's very easy to skip naming your atlas. Obviously that's not a requirement to publish but it's a lot better to have named atlases in the rest of fieldpapers.org than untitled ones. Maybe a modal after MAKE ATLAS is clicked if a name was not already entered?

**Comment by ian-ross** [comment]
@ericsoco Thanks for the comments!

If I understand what you're saying about the bounding box remaining fixed in size as you add rows and columns, it's actually rather tricky.  The aspect ratios of the individual atlas pages are fixed by paper size and orientation.  That means that if you start with a 2 row x 3 column grid (for example) and add a row, you *can't* have the same bounding box afterwards: 2 x 3 A4 pages can't cover an area with the same aspect ratio as 3 x 3 A4 pages.

I'm not sure there's a *best* answer for dealing with this, but it seems to me that an intuitively reasonable way is that: if you add a row, the vertical extent of the grid remains the same and is just divided into one more cell, and conversely if you add a columne, the horizontal extent remains the same and is just divided; in the "other" direction, the size of the grid necessarily shrinks to keep the page aspect ratios fixed.

Does that make sense?  If you can think of a better way of dealing with this, we'd love to hear it!

And I take your point about atlas names: we'll have to come up with a way of gently persuading users to name their atlases...  And we might be able to do the UTM grid reasonably soon.  @linzjax has more than a month left on her internship and she's making great progress, so we might be able to fit it in.

**Comment by ericsoco** [comment]
@ian-ross ah yeah. Good point re: aspect ratios. Your suggestion sounds like the closest thing I can imagine. Think of it from the perspective of someone trying to print a map -- they're more concerned with bounds of the physical area to be mapped than with the aspect ratio of the medium on which the maps will be printed.

Therefore, I'd advocate enlarging the area as necessary to accommodate the updated number of pages + resulting aspect ratio, to ensure all of the original map area fits within the page. If the user needs to tighten that up, she can do that after adding/removing rows/columns. Better than accidentally cropping that street she really needed in her atlas.

**Comment by mojodna** [comment]
Awesome.

A couple quick things that aren't really experiential, but will expedite merging:

* the GADM overlay option is going away (per the Red Cross)
* Basemap needs to be a combobox (dropdown + text input) to support alternate tilesets that aren't included in the presets

**Comment by ericsoco** [comment]
@ian-ross I just realized that what I was requesting (the area selection-then-pagination workflow) is essentially [this issue](https://github.com/fieldpapers/fieldpapers/issues/146). Would be excellent if you can work that in here.

**Comment by linzjax** [comment]
Hi all. I incorporated some of the suggestions:
 - removed GADM
 - made the basemap a combobox)
 - moved the row col buttons onto the map
 - made the search text bigger

I also did some experiments with tabs instead of the accordion on separate branches:
screen shot 2016-02-17 at 5 01 38 pm screen shot 2016-02-17 at 5 02 24 pm

**Comment by dalekunce** [comment]
Looking good. 

I like the one on the tab layout on the left.

**Comment by mojodna** [comment]
I really like the solution to the accordion / tab problem: neither!

Copy suggestion: "Pin grid to map" (vs. "viewport") vs. "Pin grid to NW corner". I had to click it and then pan to understand what it did.

"map" is a bit ambiguous still -- is it the thing in the background or the thing you're interacting with?

This looks like a CSS problem where the combobox is getting cut off:

image

For the atlas title, the placeholder text could change to "Title" or "Name" and the label could go away:

image

It might also be nice to hide the Notes textarea if "Print notes" is unchecked (as it doesn't get used for anything otherwise).

**Comment by mojodna** [comment]
Can the UTM Grid checkbox add it as a layer to the preview map (to give people an idea of what they'd be getting)? It would open the door to "Add-ons" becoming more useful in the future.

The preview page is http://tile.stamen.com/utm/preview.html, the URL template `http://tile.stamen.com/utm/{z}/{x}/{y}.png`.

(I've been chatting w/ @rbanick recently about overlays and have concluded that it would be nice to be able to easily add/show them on the preview page as well, though that's out of scope for this.)

**Comment by mojodna** [comment]
From me on Gitter:

> I ran into the Mapzen Search geocoder widget recently and was pretty impressed. it includes dropdown options, which might be useful for out-of-the-way places with more prominent cousins: https://github.com/mapzen/leaflet-geocoder
>
> https://mapzen.com/documentation/search/add-search-to-a-map/ shows the different states
> it would end up in the stack of buttons near the zoom control
> i’m also wondering about moving the grid resize controls to the top left of the viewport
> i didn’t notice them at first because most everything else is taking place on the top-left
> (and the grey is fairly similar to OSM’s land color. that or my colorblindness is kicking in)
> if you moved them above the zoom controls it would form an upside-down L shape and increase their prominence

From @linzjax:

> Having the search under the zoom would also free up some more space on the menu
> which would help with screen size issues

**Comment by mojodna** [comment]
Hooray!!!

**Comment by mojodna** [comment]
It's live!

**Comment by almccon** [comment]
:100: Looks great!

**Comment by dalekunce** [comment]
Fantastic work folks. 

@mojodna I agree it would be very cool to add your own overlays to the map. Maybe you have a custom geojson or something you would like people to see. Would maybe be helpful to have a couple of stock ones built in as well.

**Comment by ian-ross** [comment]
@mojodna Great! Thanks for the quick merge. I think it looks pretty cool.

**Comment by linzjax** [comment]
Yay! Thanks everyone!

**Comment by mojodna** [comment]
I spent a bunch of time w/ it yesterday afternoon debugging something else and it works really well. Seriously excellent work.

**Pull request merged**
